### ISSUE TITLE
Login from multiple devices

### ISSUE THREAD

**Issue by iurisilvio** [forkhubs/android#481]
I broke my phone and changed to a new one. I wasn't able to login in Github app because I already had a "Github Android App" registered in my "personal access tokens". After delete this token, it worked fine.

I didn't expected that, it should be a common use case to login from two Android devices.

I don't know if it is related, but I'm using the 2 factor authentication.

**Comment by RinkAttendant6** [comment]
This happened to me too and after a week of trying to figure out why I couldn't log in, I stumbled across this issue. I'm using two-factor authentication as well.

**Comment by hzsweers** [comment]
This is resolved in the latest master. GitHub's old login mechanism no longer supports two-factor auth. When we release the new version this will be resolved with it.
