### ISSUE TITLE
Ambiguous entries in Italian translation

### ISSUE THREAD

**Issue by kappa7194** [forkhubs/android#498]
There are two ambiguous entries in the Italian translation: both "cancel" and "delete" have been translated as "cancella", generating confusion when used together.

Below you can find two examples:

![screenshot_2014-04-02-21-53-55](https://cloud.githubusercontent.com/assets/1249988/2610019/8c76f226-bb7f-11e3-8f9c-f198951fce10.png)

![screenshot_2014-04-02-21-54-07](https://cloud.githubusercontent.com/assets/1249988/2610020/938ad546-bb7f-11e3-9998-33d88396ae92.png)

**Comment by larsgrefer** [comment]
This was fixed in #499 so this issue should be closed

**Comment by fadils** [comment]
Thanks @larsgrefer
