### ISSUE TITLE
Multitasking issue (issue pages not cached)

### ISSUE THREAD

**Issue by Djfe** [forkhubs/android#514]
If I open an issue and switch to another app (homescreen) and switch back to github after that then the issue page is still loaded but empty and the app doesn't refresh the page. I need to do it manually (reopening comment or using the menu).

Either the app should cache the issue page's content or refresh it automatically.

**Comment by jonan** [comment]
Can't reproduce, is it fixed?

**Comment by Djfe** [comment]
Sorry for my late reply
Appears to be fixed now, thx!
