### ISSUE TITLE
Keyboard keeps vanishing

### ISSUE THREAD

**Issue by GKFX** [forkhubs/android#523]
When I try to type comments on issues, the soft keyboard vanishes quite often, and is then hard to get back (I tap the menu key, the textarea and the preview/edit tabs repeatedly). At worst, the keyboard can vanish after being up for a few seconds, which is trying in the extreme.
I am using Google Keyboard, on a Huawei Y300.

**Comment by hzsweers** [comment]
Cleaning up as part of the general issue cleanup. If you have a reproducible case for us, please reopen with more details.

**Comment by GKFX** [comment]
@hzsweers This turns out to be a bug in the phone, not your app; I see it in all apps now. Definitely should be closed.

**Comment by hzsweers** [comment]
:+1:
