### ISSUE TITLE
[Feature Request] Push notification for assigned issues

### ISSUE THREAD

**Issue by jlewsader** [forkhubs/android#524]
Send a push notification when a new issue is assigned to the user

**Comment by Meisolsson** [comment]
We should talk to GitHub about this, maybe ask if they could add GCM(Google Cloud Messaging) to the e-mail service.

**Comment by hzsweers** [comment]
Push notifications would be great, but at best the app would currently have to function as a poller unless someone wants to write a backend for us that takes an auth token and beams it back to the user. Closing for now, we can revisit after the first release

**Comment by alorma** [comment]
Yes. For now i can't be done... we should wait until githubeadds gcm support
