### ISSUE TITLE
Open github link in the app

### ISSUE THREAD

**Issue by memphis518** [forkhubs/android#525]
If you click on a link to github, you can select github as the default application but it still opens up in the browser.  Have it open up in the app which will allow you to bypass needing to authenticate again.

**Comment by larsgrefer** [comment]
IMO this is done yet. On my Phone the current GitHub-App opens and shows all links to GitHub

(Tested with the 'view on GitHub'-links in e-mails sent from github)

**Comment by hzsweers** [comment]
Should be covered by #565
