### ISSUE TITLE
GitHub links don't offer the app from K9 Mail

### ISSUE THREAD

**Issue by chmac** [forkhubs/android#526]
When I receive a notification email from GitHub and tap on the link to "View this on GitHub", I get a list of browsers as a choice, but not the GitHub app. However, if I tap and hold on the link, then choose Open Link, I now have a choice of apps including the GitHub app. Maybe a bug in K9 Mail or could it be in the GitHub app?

**Comment by hzsweers** [comment]
Should be covered by #565
