### ISSUE TITLE
Can't login after password change: 'please enter a valid login & password'

### ISSUE THREAD

**Issue by jdtournier** [forkhubs/android#537]
I'm having the same issue as in #467, but no luck trying to fix it. I've deleted the old token from the GitHub Authorized Applications page, and then cleared the GitHub app's data on the phone, but I still can't log in. Is the token stored somewhere else on the phone? What am I missing?

This is on a Nexus 4, running 4.4.3, not rooted and fully up to date.

**Comment by hzsweers** [comment]
This should get resolved as a part of resolving #582

**Comment by jdtournier** [comment]
Indeed, hasn't been an issue for a while now. Should have closed this a while back, really...

**Comment by hzsweers** [comment]
Cool, glad it's all good now!
