### ISSUE TITLE
Inbox by Gmail view commit links don't open Github app only browsers.

### ISSUE THREAD

**Issue by sudosurootdev** [forkhubs/android#600]
The new Inbox by Gmail app have a `View Commit` link on the message title (without even opening) of every Github notification email of comments/notifications/etc. But only Browser & Chrome show as options to open them... it would be nice if Github opened up too. Opening the ones I just received and noticed this on, have `Reply to this email directly or "view it on Github"` (link in double quotes) at the bottom of the messages. Thanks... Love the app.

**Comment by hzsweers** [comment]
Just chiming in, in case anyone else wants to try their hand at this. Here what the intent it sends looks like.

![image](https://cloud.githubusercontent.com/assets/1361086/5606916/fa9d827a-93fa-11e4-8d4d-71feeac524ba.png)

**Comment by jonanp** [comment]
I looked into this a few weeks ago, it should be as simple as adding the BROWSABLE category, but never got to actually doing it.

**Comment by hzsweers** [comment]
Does #565 cover this?

**Comment by hzsweers** [comment]
Done in #565
