### ISSUE TITLE
Materialize dialogs

### ISSUE THREAD

**Issue by mustafa01ali** [forkhubs/android#666]
Appcompat-v21 gives the material treatment to a lot of things, dialogs are not one of them. Currently they look like this - 

![device-2015-01-08-212737](https://cloud.githubusercontent.com/assets/767705/5675154/50f420e0-977d-11e4-9456-e6fd113a7943.png)

All dialogs in the app should have UI as per these guidelines - http://www.google.com/design/spec/components/dialogs.html

**Comment by mustafa01ali** [comment]
@fadils @atermenji Would you guys be open to using https://github.com/afollestad/material-dialogs for this?

**Comment by fadils** [comment]
Yes, we're open.

**Comment by mustafa01ali** [comment]
Great, I'll start working on this then.

**Comment by hzsweers** [comment]
@mustafa01ali let me know if you have any issues with it. I've contributed pretty [heavily](https://github.com/afollestad/material-dialogs/graphs/contributors) to that library and know it pretty much inside and out

**Comment by mustafa01ali** [comment]
@hzsweers I have it working for the most part but there are some UI issues that need to be addressed. I do not have bandwidth to do it any time soon, if you are interested in taking a look, the code is here - https://github.com/mustafa01ali/android/tree/material_dialogs

**Comment by hzsweers** [comment]
Could you be more specific? Not really sure what I'm looking for

**Comment by hzsweers** [comment]
@mustafa01ali I'm going to close this for now. With the release of appcompat's dialogs, we're probably going to be starting from scratch on this anyway.
