### ISSUE TITLE
Minor Material UI issues

### ISSUE THREAD

**Issue by hzsweers** [forkhubs/android#681]
These are mostly low hanging fruit, but left over from the two recent drawer and tabs implementations from @Meisolsson and @mustafa01ali

* ~~Navigation Drawer should slide under the status bar as well, currently does not~~
* ~~Ripple color on drawer items is a substantially darker color than the selected color. I think it would look better to have them match.~~
* The padding between the content and the SlidingTabsLayout could be increased a little, with `clipToPadding` set to false. This is normal, to prevent the shadow from the tabs from infringing on the padding of the top item and making it appear shorter than the rest
* ~~For some reason, the ripple effect/selectors on the actionbars are now using dark colors (when it's already a dark color) instead of the original light ones. The icons also appear to be a grey color instead of white ones matching the menu icons. Seems like something probably just got messed up in styles/themes.xml.~~

I'm planning to fix these and PR them back in tonight, just creating the issue as a heads up :)

**Comment by Meisolsson** [comment]
The problem with the ripple colors is that the same colors are used eveywhere so we should try to find a way to make minimal changes.

**Comment by hzsweers** [comment]
@Meisolsson are you talking about with the nav drawer or toolbar? I've fixed the latter already in [my branch](https://github.com/hzsweers/android)

**Comment by Meisolsson** [comment]
The Toolbar, but yeah you made the fix :smile:

**Comment by hzsweers** [comment]
Sorry I haven't updated in awhile, ended up taking a sort of break over the holiday weekend here. I have 3/4 of this done, just missing the content padding below the sliding tabs. I'll pull request what I have tomorrow and save he pudding for a separate PR

**Comment by hzsweers** [comment]
Succeeded in #789
