### ISSUE TITLE
Clean up issues

### ISSUE THREAD

**Issue by Meisolsson** [forkhubs/android#700]
I just went through the issues in this repo an there are a lot of duplicates, fixed and some unimportant. I would be nice to have a better view of what needs to be done.

**Comment by fadils** [comment]
Trying my best for this.

**Comment by EzraBrooks** [comment]
I've certainly been trying to do my part.

**Comment by fadils** [comment]
@EzraBrooks you did for sure.
@Meisolsson perhaps, the fastest solution for now is to filter by "feature" label.

**Comment by fadils** [comment]
I'm gonna close this.. For more specific clean-up concern, then it can be filed in a new issue.
