### ISSUE TITLE
Better in-code documentation

### ISSUE THREAD

**Issue by EzraBrooks** [forkhubs/android#703]
From now on, we need to make sure to properly use Javadoc tags in the classes we maintain or create. The state of the documentation is terrible, and we need to be able to go back to code in the future and know exactly how it works.

**Comment by geeteshk** [comment]
I could probably take a look at this when I have some time.

**Comment by hzsweers** [comment]
You're right. @fadils and I can also look at adding a wiki page for contributing with some guidelines.
