### ISSUE TITLE
This project needs a changelog

### ISSUE THREAD

**Issue by EzraBrooks** [forkhubs/android#712]
As @kevinsawicki mentioned in #682, we should start a changelog (preferably a CHANGELOG.md in the root folder) to keep a clear log of what changes between each official build once it starts rolling out to the Play Store again.

**Comment by jonanp** [comment]
I've been working on this (while working on a stable releasable branch). It's not in the main repo yet, but you can see it here: https://github.com/jonanp/ForkHub/blob/master-upstream/CHANGELOG.md

It just contains the changes in that branch.

**Comment by MRJpcHUT** [comment]
Great idea. Something to mirror on the Play Store itself. Any plans on a iOS port of the app?

**Comment by EzraBrooks** [comment]
@jonanp, why not help with stabilising the main repo instead of your own? I understand that you've been working on ForkHub for a while, but Kevin did say that we could possibly have a monthly release schedule with this project.

**Comment by jonanp** [comment]
@EzraBrooks I spoke with @fadils and we agreed in creating a new master branch starting at v1.9.0 and cherry-pinking all the stable commits. Hopefully we can keep this new branch and delete all the meshed up history we currently have here. I've been working on this and pushing it to ForkHub, but it will be pushed to the main repo soon enough.

We need a release ASAP and the code in the current repo is far from stable and bug free, and very few people are working on stabilizing it. We have other priorities (mainly #582) so I'm working on a stable and releasable branch removing some of the current features that aren't that important now. When this is finished and we release a new version, we can concentrate on the fun stuff and merge new features.

**Comment by EzraBrooks** [comment]
All right, makes sense. I'll finish up what I can on my current project (replacing TextViews with WebViews for displaying Markdown) and then get to work on #582.

**Comment by hzsweers** [comment]
> cherry-pinking all the stable commits.

I think this is easier said than done, and will make contributors weary of putting in effort due to the lack of transparency. Why does a "stable" release need to get pushed out immediately vs. fixing existing issues and releasing later? How will bugs be tracked? Who even is going to release it...?

**Comment by jonanp** [comment]
@hzsweers I agree this is not how it should be done, but current development version is not releasable and very few people are working on testing and fixing.
The version in the Play Store has serious known bugs that are already fixed, so we should do a release ASAP, this is what this branch is for.

Hopefully everything will go back to normal in a near future.

**Comment by hzsweers** [comment]
Fair enough on releasing something with a few critical bugfixes, but last I heard no one from Github actually responded again in that discussion awhile back, so how would a release even be rolled out?

**Comment by fadils** [comment]
@hzsweers I guess we need to try first. The man already said he MIGHT help.
We do the best we can, create a changelog, get a releasable master and whatnot.
If it doesn't work, perhaps Flipboard can take it over? =)

FlipHub sounds good. Lol.

**Comment by hzsweers** [comment]
Ha, we have plenty of work on our plate as-is. I'm happy to contribute, but I don't want to waste time on it if it's never going to see the light of day, you know?

**Comment by EzraBrooks** [comment]
Well, the bright side is that we can fork it whenever we want.

**Comment by silentmoose** [comment]
This issue should be marked as resolved as the changelog is in the upstream branch soon to be implemented in main.

**Comment by fadils** [comment]
Close via #767
