### ISSUE TITLE
This project needs unit tests

### ISSUE THREAD

**Issue by wubin28** [forkhubs/android#733]
I like the integration tests of this project. I think it would be better if the gradle configuration of this project could support running unit tests. I inspected the code of this project using Android Studio and found the class NewsListAdapter was overly complex. The cyclomatic complexity of this class is 92. I wanted to add a unit test for this class and then refactor it. But I failed to run it in Android Studio and "gradle test" command in the terminal. Unit tests are running faster than integration tests without connecting to a real Android phone or an emulator.

**Comment by EzraBrooks** [comment]
I agree. Unit tests would make it much easier to de-clutter some of the overly-complex classes in the project (which there are quite a few of, it seems).

**Comment by wubin28** [comment]
After referring to the blog (https://sites.google.com/a/android.com/tools/tech-docs/unit-testing-support), I changed the version of Android gradle plugin to be 1.1.0 and added junit in the dependencies. I added a trivial test NewsListAdapterTest.testUpdate(). Now both the unit test and the original integration tests can be run smoothly in the Android Studio. Pull request has been submitted.
