### ISSUE TITLE
HTML is shown in the login header

### ISSUE THREAD

**Issue by amire80** [forkhubs/android#735]
My phone is set to Hebrew. I see HTML code in the header of the login screen.

**Comment by jonan** [comment]
Just fixed it in ForkHub https://github.com/jonan/ForkHub/commit/146e2fdfd25dd1f544a939e09cf7cf78240134ba

**Comment by hzsweers** [comment]
Cherrypicked @jonan's change back in fb35bb9e7fc421693b4f8cbc8f1775e94c2b1738
