### ISSUE TITLE
Latest code is still unavailable on Google Play

### ISSUE THREAD

**Issue by pjhades** [forkhubs/android#736]
The current version on Google Play is 1.9.0 updated on Feb 20 2014. This version has syntax highlighting problems in the source editor, where some files like `.c` and `.hpp` cannot be highlighted. I see that the committing history of file /app/assets/source-editor.js shows the CodeMirror has been upgraded:

> Update CodeMirror to v4.8.0 jonan authored on Dec 2, 2014  fadils committed on Dec 14, 2014

I have tried to run the app through Android Studio and the problem is gone. Maybe the app on Google Play should be updated. Thanks.

**Comment by jonan** [comment]
The official app is not being updated and it doesn't look like it will in the near future.

You can give [ForkHub](https://play.google.com/store/apps/details?id=jp.forkhub) a try, it's are actively maintained fork: https://github.com/jonan/ForkHub.

**Comment by pjhades** [comment]
Seems cool, I'll try it, muchas gracias :)

**Comment by alorma** [comment]
You can try another apps too:

https://github.com/alorma/Gitskarios

**Comment by pjhades** [comment]
Thanks you guys :+1:

**Comment by jonan** [comment]
@fadils I don't think this issue should be closed until the app is updated, even if we can't do anything about it. Just for other people to see if they come here for information.

Or maybe you could create another issue more specific, kind of "The Google Play version isn't being updated" and explain the situation or something like that.

**Comment by fadils** [comment]
I thought this is a duplicate somewhere..?
Anyway, I'll reopen it regardless.

Thanks for reminder.

**Comment by alorma** [comment]
Yes please.

Why the google play not updated?

**Comment by Daniel-Diaz** [comment]
I add myself here. What is keeping GitHub from upgrading its app?

**Comment by agargiulo** [comment]
:+1: for updating the app on Google Play. Or at least a reason why it isn't going to be updated.

**Comment by Vorgone** [comment]
Has anyone attempted to contact GitHub, to get some answers?

**Comment by agargiulo** [comment]
Isn't that what this thread is doing though? It's an open issue on a repo they own. In theory, someone who works there is getting notifications for these issues.

**Comment by Vorgone** [comment]
Technically yes, however this issue has been open for 25 days, and it's been over a year since any code has been released to the Play store.  I think at this point it's reasonable to reach out to GitHub either over the phone or through email.  I'm wondering if anyone else has reached out to them, before I do.

**Comment by agargiulo** [comment]
That's a fair point. At this point I'd say go for it and let us know what you hear back?

**Comment by jonan** [comment]
We are in contact with GitHub (https://github.com/github/android/issues/682#issuecomment-70918107).
We are working on a solution.

**Comment by agargiulo** [comment]
Are you actually working with them though? The issue was closed and the thread seems to not have actually solved anything. But it does provide answers somewhat. It appears that the development process for the app fell apart and I would imagine that makes it hard to release things with any amount of certainty that they'll not break as soon as people start using them.

**Comment by Vorgone** [comment]
Thanks @jonan, that is kind of what I had expected their answer might be.  
I think at the very least we should update the Readme.md, and let people know that they're currently no plans for future releases of the code.

**Comment by jonan** [comment]
We are. @fadils, @kevinsawicki and I are trying to find the best solution.

Anyhow, GitHub will stop supporting this app officially, so the solution will be to continue development in [ForkHub](https://play.google.com/store/apps/details?id=jp.forkhub) or create a new repository and continue there.

**Comment by Vorgone** [comment]
I'm satisfied that this issue can be closed.  I'll send a pull request adding a note to the Readme.md which should mitigate anyone else from opening more issues on this matter.

**Comment by Vorgone** [comment]
Looks like some exciting things are happening.  The owner of the repository has changed and the GitHub app looks to have been pulled from the Play Store.

**Comment by barrystaes** [comment]
> the GitHub app looks to have been pulled from the Play Store.

So i noticed the day before.. :/
@kevinsawicki I would really prefer the app entry remaining available to explain things somewhat..

**Comment by hzsweers** [comment]
I'm closing this for now. This will be released when it's ready. At that time, we can figure out if and what we want to do with the original version on the play store. In the meantime, feel free to use any of the many forks that people have uploaded or clone and build this from source.
