### ISSUE TITLE
Forks

### ISSUE THREAD

**Issue by alorma** [forkhubs/android#763]
Since app will not be updated in Play Store (, https://github.com/github/android/issues/736), readme or wiki can contain a section with forks or other github apps.

Maybe with vote system.

**Comment by hzsweers** [comment]
Looks like https://github.com/forkhubs/android (aka this repo) is now the new official fork

**Comment by Vorgone** [comment]
Since the app no longer has an official version, I don't think we need to have a page listing the forks.  Such a page would be difficult to maintain, anyways as forks come and go almost daily.

**Comment by fadils** [comment]
Actually, we're releasing soon.
