### ISSUE TITLE
provide capabilities to use with gogs and gitlab code hosting software

### ISSUE THREAD

**Issue by robinpaulson** [forkhubs/android#766]
Both are free software code hosting repositories, which the developer can host on their own server.

**Comment by alorma** [comment]
I will implement that on my app soon:

https://play.google.com/store/apps/details?id=com.alorma.github

But it's not ease to achive this, because the Rest api (data source) is completly different

**Comment by jonan** [comment]
This is way out of the scope of this app. We don't even have support for multiple GitHub accounts!

**Comment by alorma** [comment]
Not supporting multi accounts is a bad point for this app :p

**Comment by jonan** [comment]
Multiple accounts and GitHub Enterprise support is on the roadmap.
Other services are not, it's simply too much work (if at all possible).
