### ISSUE TITLE
eclipse .project file missing

### ISSUE THREAD

**Issue by bhupesh-pant** [forkhubs/android#769]
Android eclipse .project file missing in app folder. Any pointers to build it via eclipse

**Comment by larsgrefer** [comment]
This app is not meant to be build with eclipse.

The Eclipse ADT-plugin is not longer maintained by Google/AOSP. The new and official way to develop and build android apps is AndroidStudio and Gradle.

More information can be found here:
- http://developer.android.com/sdk/index.html
- http://developer.android.com/tools/studio/index.html

**Comment by fadils** [comment]
We're no longer support Eclipse build. Sorry.
:disappointed:
