### ISSUE TITLE
Fails to show issues in some projects

### ISSUE THREAD

**Issue by Maximus5** [forkhubs/android#795]
The problem was found with issues of
https://github.com/git-for-windows/git/issues

I can file new issue but can't view existing or even just created one. Just empty field is shown.

![screenshot_2015-04-24-15-27-01](https://cloud.githubusercontent.com/assets/1222388/7318753/ec5120ca-ea97-11e4-83c6-9106a00fee39.png)

**Comment by StefMa** [comment]
Maybe an loading issue?! 
I have noticed that there is no loading indicator or something... Maybe the page isn't loading. Maybe wait longer?!

**Comment by jonan** [comment]
The issue is known and fixed #583, but the version in Google Play hasn't been updated #736
