### ISSUE TITLE
App not showing up in Google Play Store

### ISSUE THREAD

**Issue by rsvp** [forkhubs/android#802]
Has the app been rejected by Google, or retracted by the developers?

Here is the latest search results at the store:
https://play.google.com/store/search?q=github&c=apps

Note that there is https://play.google.com/store/apps/details?id=jp.forkhub
"Forkhub for Github" which is a fork of the current repo 
at https://github.com/jonan/forkhub -- 
which is not identical to https://github.com/forkhubs/android 
mentioned in the **official** GitHub blog:
https://github.com/blog/1187-github-android-app-released 

Any cause for concern?

**Comment by hzsweers** [comment]
Github removed it, and this is now a community project. We are working on getting a new release out soon. See #772 for more info
