### ISSUE TITLE
Authenticator code not working

### ISSUE THREAD

**Issue by crispi7** [forkhubs/android#808]
Hi,
I have just noticed that using an authenticator code to log in does not work. It shows a message like:"wrong username and password". Nonsense message because the username and password are checked earlier. Anyway, there is no problems login into the account from the website
Tell me if you need more info.

**Comment by fadils** [comment]
Hey, it's probably related to #582.
We haven't had the chance to update it, yet.

We'll let you know for sure.

Thanks!

**Comment by hzsweers** [comment]
Same issue, let's keep the discussion in #582
