### ISSUE TITLE
Unable to login (2FA)

### ISSUE THREAD

**Issue by Elegant996** [forkhubs/android#817]
I can't login using the app on one of my devices, I could last week but not anymore. Keeps prompting me for a "proper" Username/Password combo. I've tried my Username and Email to no avail and yes the password is correct. My 2FA is also correct. I've also tried wiping out the app settings and even porting the app settings from a working device over which still prompts me for my credentials and claims they are invalid.

**Comment by Meisolsson** [comment]
This is because of a change in the GitHub API. We are working on fixing it but it will take some time.

**Comment by landstander668** [comment]
I was able to work around this issue by deleting my Personal Access Token (via the web interface) for the android app, and then attempting to login again. The token was automatically recreated, and the app now appears to be working normally.

**Comment by bencromwell** [comment]
@landstander668 thanks for posting the workaround. Had reinstalled the app before finding this issue thread. 

The Android app is otherwise completely inaccessible to 2FA enabled users.

**Comment by Meisolsson** [comment]
Should be fixed with #831 since we use the website login

**Comment by babineaum** [comment]
Agree with @landstander668 this is a huge missing component when you set up 2FA. You must delete the PAT before entering in the 2FA token.
