### ISSUE TITLE
Auth token lookup failed

### ISSUE THREAD

**Issue by yssource** [forkhubs/android#832]
Hi, I'm from China. I tried to debug the tool on my cellphone, and got the following issue.
3928-5053/com.github.mobile:auth D/GHAccountAuthenticator﹕ Retrieving OAuth2 token
06-28 21:34:43.957    3876-5011/com.github.mobile E/GitHubAccount﹕ Auth token lookup failed
    java.io.IOException: org.eclipse.egit.github.core.client.RequestException: Validation Failed (422): OauthAccess resource with 'description' field already exists

**Comment by hzsweers** [comment]
Hi, we're in the process of fixing oauth right now, so please bear with us
for a bit.
