### ISSUE TITLE
Authorize Gitskarios

### ISSUE THREAD

**Issue by alorma** [forkhubs/android#838]
Hi.

I use Gitskarios application to access GitHub, and sometime si want to comment in issues for this repository. But since GitHub added 3rd party app restrictions for organizations, i cannot comment or create issues (from app, i can from website). So please, can you authorize Gitskarios?

There are some tips i get from gGitHub team:

> There are a few ways to approve an application:
> 
> 1. you visit the application's website and try to sign in yourself. As a part of the sign in process, you > should be able to approve the application, even without completely signing into the app:
> 
> https://help.github.com/articles/requesting-organization-approval-for-third-party-applications/
> 
> 2. if you already authorized the application yourself, then you can following these instructions to > > > > approve the application from your settings:
> 
> https://help.github.com/articles/requesting-organization-approval-for-your-authorized-applications/
> 
> 3. if a member of the organization requested approval, you can approve it by following these > > > >  > instructions:
> 
> https://help.github.com/articles/approving-third-party-applications-for-your-organization/

**Comment by hzsweers** [comment]
We're currently looking at that now, will let you know what we decide
(either white listing your app or just removing restrictions in general).

**Comment by hzsweers** [comment]
@alorma I've disabled third party app restrictions, so you should be good to go.

**Comment by hzsweers** [comment]
Do you know if there's an endpoint in github's API for checking if an app is restricted? Would be nice to show a more descriptive error message to users than just "404" so they can know to ask

**Comment by alorma** [comment]
As far as i know, there's no API for third party restrictions...  :disappointed:

**Comment by alorma** [comment]
And yes, i can publish now, thanks
