### ISSUE TITLE
The token attribute is deprecated in many OAuth Authorizations API responses

### ISSUE THREAD

**Issue by Leaking** [forkhubs/android#842]
[The token attribute is deprecated in many OAuth Authorizations API responses](https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization)

In the current source code,the authorization workflow is like below.

+ 1 You use username and password to create a token and get the new token in response.
+ 2 You logout.And the App trys to get existing token from server but he API never return token from now on because token attribute is deprecated. 
+ 3 Getting existing token fail, so the App try to create a new token again like the step 1，but the token has already existed and is will response a 422  response .

```JSON
{
    "message": "Validation Failed",
    "errors": [
        {
            "resource": "OauthAccess",
            "code": "already_exists",
            "field": "description"
        }
    ],
    "documentation_url": "https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization"
}
```
 
+4 So after you logout ,and login again,From now on you will always use Basic Authorization and send username and password every time.

**Comment by Leaking** [comment]
We can't recreate the same token again，maybe we can delete the token AND create it again。

**Comment by hzsweers** [comment]
There's a PR open for this already and an existing issue. We'll probably have it in over the next few days.
