### ISSUE TITLE
Impossible to login

### ISSUE THREAD

**Issue by FacedownPhp** [forkhubs/android#847]
Hi,

When I enter my email, password (40 character length, generated from LastPass) and correct code from Authy, it tells me, "please enter a valid login & password" even though I entered correct credentials and code. When I enter credentials directly to browser it is good. 

Password match, no character is trimmed, same behaviour when I enter username instead of email, I let LastPass to directly enter my password then I copy and paste, nothing helped.

Every advice is appreciate. Thank you

**Comment by hzsweers** [comment]
This is fixed in master, the last version GitHub had on the play store
won't work with 2-factor authentication anymore.

**Comment by FacedownPhp** [comment]
Thank you and sorry for unnecessary issue.

**Comment by hzsweers** [comment]
No worries!
