### ISSUE TITLE
Getting a 404 on login

### ISSUE THREAD

**Issue by aashrairavooru** [forkhubs/android#849]
Logged into the app for the first time, got a 404 page after the usual github login page

![screenshot_2015-07-26-14-12-38](https://cloud.githubusercontent.com/assets/7071610/8893120/a48dd7b8-33a0-11e5-93d2-b82219156e2b.png)

**Comment by hzsweers** [comment]
We need more info than this.

Is this the latest master?

Reproducible?

What kind of authentication?

If you built from master, did you set up github.properties correctly?

**Comment by aashrairavooru** [comment]
1)Yes this is the latest master
2)I was taken to the github web login page

Looks like i didn't set up the github.properties file,can this be in the readme or in a separate building guide

**Comment by hzsweers** [comment]
We're working on adding something (there's an issue for it), but you
should've seen warnings in the gradle logs too

**Comment by aashrairavooru** [comment]
been a long time since i saw gradle logs for anything, anyways will be waiting for the guide
